# also see https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1200]
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
        exclude: tsconfig.json
      - id: check-merge-conflict
      # - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: destroyed-symlinks
      # - id: detect-aws-credentials
      - id: detect-private-key
      - id: pretty-format-json
        exclude: tsconfig.json
        args: [--autofix, --no-sort-keys]
  # https://github.com/google/yamlfmt/blob/main/docs/pre-commit.md
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
  # - repo: https://github.com/psf/black
  #   rev: 24.3.0
  #   hooks:
  #     - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
  # Problem: wants to install node (and markdownlint-cli) but fails
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: "v0.45.0"
  #   hooks:
  #     - id: markdownlint
  #       args: ["-f"]
  #       stages: [pre-commit]
  #       node: 22.19.0
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.6
  #   hooks:
  #     - id: bandit
  # https://docformatter.readthedocs.io/en/latest/usage.html
  # docformatter --wrap-summaries 120 --wrap-descriptions 120 -r -i src
  # - repo: https://github.com/PyCQA/docformatter
  #   rev: v1.7.5
  #   hooks:
  #     - id: docformatter
  #       additional_dependencies: [tomli]
  #       language: python
  #       args: [--in-place --config ./pyproject.toml]
  # - repo: https://github.com/astral-sh/ruff
  #   rev: v0.3.0
  #   hooks:
  #     - id: ruff
  # this take too much time to run this every commit (tp)
  # - repo: https://github.com/dmar1n/lazy-log-formatter
  #   rev: 0.8.0
  #   hooks:
  #     - id: lazy-log-formatter
  #       args: ['--fix', 'src', 'tests', 'examples', 'tests_broken']
  # Problem: no option to cd to ./rust
  # - repo: https://github.com/EmbarkStudios/cargo-deny
  #   rev: 0.18.5
  #   hooks:
  #     - id: cargo-deny
  #       args: ["--all-features", "check"]
  - repo: local
    hooks:
      - id: maturin-develop
        name: maturin develop
        entry: maturin develop -E all,dev
        language: system
        files: ^(python/|src/|Cargo\.toml|pyproject\.toml)
        pass_filenames: false
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]
    # - id: mypy-check
    #   name: mypy type check
    #   entry: dmypy run python
    #   language: system
    #   types: [python]
    #   pass_filenames: false
